language: php

php:
    - 5.6
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update --no-interaction --no-suggest --prefer-lowest --prefer-dist

script:
    - vendor/bin/phpunit

branches:
    only:
        - master
